BEGIN TRANSACTION;
CREATE TABLE __WebKitDatabaseInfoTable__ (key TEXT NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT REPLACE,value TEXT NOT NULL ON CONFLICT FAIL);
INSERT INTO __WebKitDatabaseInfoTable__ VALUES('WebKitDatabaseVersionKey',1.0);
COMMIT;
