BEGIN TRANSACTION;
CREATE TABLE Databases (guid INTEGER PRIMARY KEY AUTOINCREMENT, origin TEXT, name TEXT, displayName TEXT, estimatedSize INTEGER, path TEXT);
INSERT INTO Databases VALUES(1,'file__0','LeadingEDJE','LeadingEDJE',1024000000,'0000000000000001.db');
CREATE TABLE Origins (origin TEXT UNIQUE ON CONFLICT REPLACE, quota INTEGER NOT NULL ON CONFLICT FAIL);
INSERT INTO Origins VALUES('file__0',1024000000);
COMMIT;
